### ISSUE TITLE
Fix build timeouts

### ISSUE THREAD

**Issue by deansheather** [cdr/nbin#11]
Currently, Travis builds are consistently failing due to going over the 50 minute cut off. We use ccache to speed up the Node.js compilation step, but I can't tell if it's working since the builds are still really long.

I tried Microsoft's CI offering (Azure Pipelines) and it's building considerably faster, although ccache doesn't seem to be speeding it up by much (or at all):
- https://deansheather.visualstudio.com/nbin/_build/results?buildId=14
- https://github.com/deansheather/nbin/blob/pipelines/azure-pipelines.yml

I'm not saying we should switch (Azure Pipelines doesn't even have a [built in cache task](https://github.com/Microsoft/azure-pipelines-yaml/pull/113#issuecomment-493113099) yet), but if we can't improve times on Travis, this seems considerably faster.

Another suggestion would be to only build node when the patch or node revision is changed. Maybe we could ask Travis to increase our build timeout as well.

**Comment by sr229** [comment]
@deansheather We can't ask Travis for a extension for build timeouts since its the hard limit, I also suggest CircleCI which is considerably as fast as Azure pipelines as well.

**Comment by deansheather** [comment]
@sr229 I'm unfamiliar with CircleCI, is it easy to setup? Also, what's their build timeout?

**Comment by sr229** [comment]
@deansheather as far as my knowledge goes, yes. We can compile using Docker images directly or use a VM image as well.

**Comment by kylecarbs** [comment]
This has been fixed! Our build timeout is 2hrs now.
