### ISSUE TITLE
how to extract code-server nbin file?

### ISSUE THREAD

**Issue by lab4quant** [cdr/nbin#37]
Hello, how to extract released `code-server` [binary file](https://github.com/cdr/code-server/releases)?
I'm interested in the files inside, thank you!

**Comment by code-asher** [comment]
We don't currently have any ready-built tools to extract the files. You
could modify `nbin.ts` to read in your target binary then iterate
through `fs` and write each file out to the disk.

**Comment by lab4quant** [comment]
@code-asher, thanks, let me try

**Comment by code-asher** [comment]
Hey, sorry I didn't see this; GitHub doesn't send emails for edits. 

Something like this should work:
```
import * as fs from "fs"
import { readString } from "../common/buffer"
import { ReadableFilesystem } from "../common/filesystem"
import { readFooter } from "../common/footer"

const binaryPath = process.argv[2]
const binaryStat = fs.statSync(binaryPath)
const nbinFd = fs.openSync(binaryPath, "r")

// Footer is located at the end of the file.
const footer = readFooter(nbinFd, binaryStat.size)

// Contains the version, mainFile and the filesystem.
const headerBuffer = Buffer.allocUnsafe(footer.headerLength)
fs.readSync(nbinFd, headerBuffer, 0, footer.headerLength, footer.headerOffset)
const version = readString(headerBuffer, 0)
const mainFile = readString(headerBuffer, version.offset)

// Maximize read performance by using the originals before any overrides.
const originalRead = fs.read
const originalReadSync = fs.readSync

const fsBuffer = headerBuffer.slice(mainFile.offset)
const readableFs = ReadableFilesystem.fromBuffer(fsBuffer, {
  readContents: (offset: number, length: number): Promise<Buffer> => {
    const buffer = Buffer.allocUnsafe(length)
    return new Promise<Buffer>((resolve, reject) => {
      originalRead(nbinFd, buffer, 0, length, offset + footer.contentOffset, (err, _, buffer) => {
        if (err) {
          return reject(err)
        }

        resolve(buffer)
      })
    })
  },
  readContentsSync: (offset: number, length: number): Buffer => {
    const buffer = Buffer.alloc(length)
    originalReadSync(nbinFd, buffer, 0, length, offset + footer.contentOffset)
    return buffer
  },
})

// From here you'd get the top-level directories and then recursivelyiterate
// through them and write everything out to the disk.

// The base path will be different depending on how code-server was built. For
// our Travis builds that's /src. I'm not sure why / doesn't work; that's
// probably a bug.
const dirs = readableFs.readdirSync("/src")
console.log(dirs)
```

Save this file as `./src/patches/extract.ts`.

You can compile it or you can run it directly with `ts-node` with something like:
```
ts-node ./src/patches/extract.ts ~/dwn/code-server2.1692-vsc1.39.2-linux-x86_64/code-server
```

To actually answer your question, we write the length of the file system at the binary. That length tells us where the header is. Everything in between the header and the footer is the file system. Each file has a header describing how long it is and the offset from the start of the file system so those two values can be used to read the file from inside the binary.

**Comment by lab4quant** [comment]
@code-asher , thanks a lot, let me try

**Comment by lab4quant** [comment]
@code-asher, i did some quick test, it doesn't work on windows, i tried both `./src` and fullpath
in `src\common\filesystem.ts -> getFilesystem`, it tries to navigate from `C:` to `User`, then stopped(break)
there maybe bug in `filesystem.ts`

**Comment by code-asher** [comment]
Ahh yeah there's no Windows support yet. We probably have more than a
few bugs when it comes to Windows. I'm not sure yet when we'll have time
to work on that.

**Comment by lab4quant** [comment]
@code-asher, ok, understood, i'll do some test this week on mac

**Comment by lab4quant** [comment]
@code-asher, sorry for the late update, i tested on mac, it's the same

i put `vscode` in Downloads, and `code-server` inside `vscode/src/vs` (renamed as server)

in `extract.ts`, I use `const dirs = readableFs.readdirSync("/Users/xxxx/Downloads/vscode/src/")`

```sh
/Users/xxxx/Downloads/nbin/src/common/error.ts:2
  const e = new Error("File not found")
            ^
Error: File not found
    at Object.exports.createNotFound (/Users/xxxx/Downloads/nbin/src/common/error.ts:2:13)
    at ReadableFilesystem.readdirSync (/Users/xxxx/Downloads/nbin/src/common/filesystem.ts:157:13)
    at Object.<anonymous> (/Users/xxxx/Downloads/nbin/src/patches/extract.ts:50:25)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Module.m._compile (/usr/local/lib/node_modules/ts-node/src/index.ts:814:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Object.require.extensions.<computed> [as .ts] (/usr/local/lib/node_modules/ts-node/src/index.ts:817:12)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
```

**Comment by lab4quant** [comment]
@code-asher , i printed `this.directories` inside `cd` method of `filesystem` class, this is what i found, there has to be some sort of hard code, yet i couldn't find using vscode search

input for `getFilesystem`: `/Users/xxxx/Downloads/vscode/src/`
it's trying to get `/Users/travis/build/`
```
Map {
  'Users' => ReadableFilesystem {
    directories: Map { 'travis' => [ReadableFilesystem] },
    files: Map {},
    existsSync: [Function]
  }
}
Users
Map {
  'travis' => ReadableFilesystem {
    directories: Map { 'build' => [ReadableFilesystem] },
    files: Map {},
    existsSync: [Function]
  }
}
```

**Comment by code-asher** [comment]
Ohh, right, you've got the Mac build. That explains why the base path is
/Users/travis/build. You should be able to do
readdirSync("/Users/travis/build") and go from there to extract all the
files right?

/Users/xxxx/Downloads/vscode/src won't work because that's the path on
your filesystem, not the path inside the binary. But if you start from
/Users/travis/build you should be able to recurse through all the
directories and write out all the files.

**Comment by lab4quant** [comment]
@code-asher , thanks a lot, the fullpath inside the binary file is:
`/Users/travis/build/cdr/code-server/build/code-server2.1698-vsc1.41.1-darwin-x86_x64-built`
